### ISSUE TITLE
Rnpkeys : user is unable to create/append keys to custom keyring.

### ISSUE THREAD

**Issue by MohitKAgnihotri** [rnpgp/rnp#70] opened 2017-05-06 10:48 UTC
The user is unable to create new keys in a custom user provided keyring. 
`usage: ./rnpkeys --generate-key --keyring=max`
expected output: new keyring with name "maxpub & maxsec" is created in the HOMEDIR.
Test case; `rnpkeys_generatekey_verifykeyRingOptions`

**Comment by MohitKumarAgniotri** [comment] 2017-05-09 10:31
@ronaldtse, @shaunwheelhouse: Please help me defining the behaviour for option `--keyring`.
Many test case are failing for this item,

**Comment by ronaldtse** [comment] 2017-05-12 03:50
I think @shaunwheelhouse is finishing off his branch for a consistent `homedir` and `keydir`, perhaps his branch will fix this issue?

**Comment by dewyatt** [comment] 2017-05-15 20:50
Probably related: https://github.com/riboseinc/rnp/issues/21

**Comment by dewyatt** [comment] 2017-08-13 17:28
I'm giving this a regression label since it looks like the `--keyring` option is completely unused now in the code base (though it's still accepted as a valid option, it appears to have no effect).

Given that GPG does support this option, we may want to consider supporting it again I guess.

**Comment by ni4** [comment] 2022-11-21 14:58
Let's close this as not releveant anymore: we have `--homedir` and `--keyfile` options, which should be sufficient for all uses. If some edge case is not covered - we'd create a separate issue/PR.

**Closed by ni4** 2022-11-21 14:58 UTC
Labels: bug, regression
