### ISSUE TITLE
Edge case: RNP_ERROR_SIGNATURE_INVALID for good sig from key with no uid

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1102] opened 2020-04-19 09:43 UTC
I see error code RNP_ERROR_SIGNATURE_INVALID when verifying a signature, if only a stripped version of the key is available.

This is the message
https://lists.gnupg.org/pipermail/gnupg-announce/2020q1/000444.html

It was signed by key ID FF80AE9D1DEC358D.

keys.openpgp.org has a stripped key for it, available here:
https://keys.openpgp.org/search?q=FF80AE9D1DEC358D

That key doesn't not contain any user id. The policy of that keyserver is that opt in is required to distribute the user id, and apparently that opt in wasn't given.

When importing this stripped key into RNP, and verifying this message, we get error RNP_ERROR_SIGNATURE_INVALID

However, the signature seems to be valid. If importing a better key (one that includes the user id), then RNP reports a good signature.

This is certainly an edge case. I'm guessing that RNP detects the missing uid during verification, and concludes it's a bad sig. Would it make sense for RNP to report a good sig?

I'll attach a zip file that contains the message, the stripped key from keys.openpgp.org (without user id), and a stripped key that I made with gnupg (includes user id).

**Comment by kaie** [comment] 2020-04-19 09:46
[sig-inval-issue-1102.zip](https://github.com/rnpgp/rnp/files/4498745/sig-inval-issue-1102.zip)

**Comment by ni4** [comment] 2020-04-19 12:22
Thanks for the report again, @kaie. That really helps to find corner cases from the real world instead of theoretical ones :) Currently this behavior is by logic - to mark public key as valid it requires to have at least one valid non-expired self-certification (i.e. needs keyid), or direct-key signature. But looks like binding must be also taken in account. I will provide fix for this soon.

**Comment by ni4** [comment] 2020-04-26 18:47
@kaie Could you please provide a raw data from this email for verification? I tried to extract it from email according to OpenPGP/MIME standard for few times but looks like I missed some spaces/EOLs/correct quoted-printable translation somewhere.

**Comment by kaie** [comment] 2020-04-28 00:14
[raw-data-issue-1102.zip](https://github.com/rnpgp/rnp/files/4542666/raw-data-issue-1102.zip)

Here is the extracted signed message and the detached signature.

**Comment by ni4** [comment] 2020-04-28 10:31
@kaie Thanks. I though it is needed to decode quoted-printable first. Anyway, now confirmed - it is verified successfully with the recent changes (available in yet draft PR #1108.).

How is your schedule, are you waiting for some features from us or still have other things to do? Since we have some lag between implementation and merging to master, I can provide you a separate branch with all tested/believed to work well commits with new features.

**Comment by ni4** [comment] 2020-04-29 17:27
Just some thoughts on this case: primary key which expires should never have non-expiring subkeys (and, more - their expiration date should be not more then primary key expiration date).
Otherwise we may just strip userid/certifications and got valid key for signature verification for as long as subkey is not expired.

**Closed** 2020-05-03 11:42 UTC

**Comment by kaie** [comment] 2020-05-10 21:26
Thanks for fixing. I haven't yet tested this scenario again. We've decided not to import keys without user IDs for now.
